spring.application.name=bcm_info_val
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/borj
spring.datasource.username=postgres
spring.datasource.password=Othmane123@
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=borjref


ia.callback.api-key=${IA_CALLBACK_KEY:cle123456}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always